<a href="https://colab.research.google.com/github/daekee0325/Data-Analysis/blob/master/2020_07_15_pandas_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
values_1 = np.random.randint(10, size=10)
values_2 = np.random.randint(10, size = 10)

In [3]:
print(values_1)
print(values_2)

[9 6 0 5 0 3 5 8 4 0]
[3 7 4 0 1 4 4 0 5 6]


In [4]:
years = np.arange(2010, 2020)
print(years)

[2010 2011 2012 2013 2014 2015 2016 2017 2018 2019]


In [5]:
groups = ['A','A','B','A','B','B','C','A','C','C']
len(groups)

10

In [6]:
df = pd.DataFrame({'group':groups, 'year':years,'value_1': values_1, 'value_2':values_2})
df

group  year  value_1  value_2
0     A  2010        9        3
1     A  2011        6        7
2     B  2012        0        4
3     A  2013        5        0
4     B  2014        0        1
5     B  2015        3        4
6     C  2016        5        4
7     A  2017        8        0
8     C  2018        4        5
9     C  2019        0        6

In [7]:
df.query('value_1<value_2')

group  year  value_1  value_2
1     A  2011        6        7
2     B  2012        0        4
4     B  2014        0        1
5     B  2015        3        4
8     C  2018        4        5
9     C  2019        0        6

In [8]:
new_col = np.random.randn(10)

In [9]:
df.insert(2, 'new_col',new_col)


In [10]:
df

group  year   new_col  value_1  value_2
0     A  2010  3.149183        9        3
1     A  2011  0.532873        6        7
2     B  2012  0.213676        0        4
3     A  2013 -1.194596        5        0
4     B  2014 -0.151651        0        1
5     B  2015 -1.090184        3        4
6     C  2016  1.611263        5        4
7     A  2017 -0.272470        8        0
8     C  2018 -0.542211        4        5
9     C  2019 -0.184487        0        6

In [11]:
df['cumsum_2'] = df[['value_2','group']].groupby('group').cumsum()
df

group  year   new_col  value_1  value_2  cumsum_2
0     A  2010  3.149183        9        3         3
1     A  2011  0.532873        6        7        10
2     B  2012  0.213676        0        4         4
3     A  2013 -1.194596        5        0        10
4     B  2014 -0.151651        0        1         5
5     B  2015 -1.090184        3        4         9
6     C  2016  1.611263        5        4         4
7     A  2017 -0.272470        8        0        10
8     C  2018 -0.542211        4        5         9
9     C  2019 -0.184487        0        6        15

SMPLE

In [12]:
Sample1 = df.sample(n=3)
Sample1

group  year   new_col  value_1  value_2  cumsum_2
5     B  2015 -1.090184        3        4         9
3     A  2013 -1.194596        5        0        10
9     C  2019 -0.184487        0        6        15

In [13]:
Sample2 = df.sample(frac=0.5)
Sample2

group  year   new_col  value_1  value_2  cumsum_2
5     B  2015 -1.090184        3        4         9
4     B  2014 -0.151651        0        1         5
9     C  2019 -0.184487        0        6        15
7     A  2017 -0.272470        8        0        10
3     A  2013 -1.194596        5        0        10

In [14]:
df['new_col'].where(df['new_col']>0,0)

0    3.149183
1    0.532873
2    0.213676
3    0.000000
4    0.000000
5    0.000000
6    1.611263
7    0.000000
8    0.000000
9    0.000000
Name: new_col, dtype: float64

In [15]:
np.where(df['new_col'] >0, df['new_col'], 0)

array([3.14918309, 0.53287291, 0.21367595, 0.        , 0.        ,
       0.        , 1.61126254, 0.        , 0.        , 0.        ])

isin

In [16]:
years = ['2010','2014','2015']

In [17]:
df[df.year.isin(years)]

group  year   new_col  value_1  value_2  cumsum_2
0     A  2010  3.149183        9        3         3
4     B  2014 -0.151651        0        1         5
5     B  2015 -1.090184        3        4         9

In [18]:
df.loc[:2, ['group','year'] ]

group  year
0     A  2010
1     A  2011
2     B  2012

In [19]:
df.loc[[1,3,5],['year','value_1']]

year  value_1
1  2011        6
3  2013        5
5  2015        3

In [20]:
df['value_1']

0    9
1    6
2    0
3    5
4    0
5    3
6    5
7    8
8    4
9    0
Name: value_1, dtype: int64

In [21]:
df.value_1.pct_change()

0         NaN
1   -0.333333
2   -1.000000
3         inf
4   -1.000000
5         inf
6    0.666667
7    0.600000
8   -0.500000
9   -1.000000
Name: value_1, dtype: float64

In [22]:
df.value_1.sort_values()

2    0
4    0
9    0
5    3
8    4
3    5
6    5
1    6
7    8
0    9
Name: value_1, dtype: int64

In [23]:
df.value_1.sort_values().pct_change()

2         NaN
4         NaN
9         NaN
5         inf
8    0.333333
3    0.250000
6    0.000000
1    0.200000
7    0.333333
0    0.125000
Name: value_1, dtype: float64

In [24]:
df['rank_1'] = df['value_1'].rank( )
df

group  year   new_col  value_1  value_2  cumsum_2  rank_1
0     A  2010  3.149183        9        3         3    10.0
1     A  2011  0.532873        6        7        10     8.0
2     B  2012  0.213676        0        4         4     2.0
3     A  2013 -1.194596        5        0        10     6.5
4     B  2014 -0.151651        0        1         5     2.0
5     B  2015 -1.090184        3        4         9     4.0
6     C  2016  1.611263        5        4         4     6.5
7     A  2017 -0.272470        8        0        10     9.0
8     C  2018 -0.542211        4        5         9     5.0
9     C  2019 -0.184487        0        6        15     2.0

In [25]:
df.select_dtypes(exclude='int64')

group   new_col  rank_1
0     A  3.149183    10.0
1     A  0.532873     8.0
2     B  0.213676     2.0
3     A -1.194596     6.5
4     B -0.151651     2.0
5     B -1.090184     4.0
6     C  1.611263     6.5
7     A -0.272470     9.0
8     C -0.542211     5.0
9     C -0.184487     2.0

In [26]:
df.replace({'A':'A_1','B':'B_1'})

group  year   new_col  value_1  value_2  cumsum_2  rank_1
0   A_1  2010  3.149183        9        3         3    10.0
1   A_1  2011  0.532873        6        7        10     8.0
2   B_1  2012  0.213676        0        4         4     2.0
3   A_1  2013 -1.194596        5        0        10     6.5
4   B_1  2014 -0.151651        0        1         5     2.0
5   B_1  2015 -1.090184        3        4         9     4.0
6     C  2016  1.611263        5        4         4     6.5
7   A_1  2017 -0.272470        8        0        10     9.0
8     C  2018 -0.542211        4        5         9     5.0
9     C  2019 -0.184487        0        6        15     2.0

In [27]:
def color_negative_values(val):
  color = 'red' if val < 0 else 'black'
  return 'color : %s' %color

In [28]:
df[['new_col']].style.applymap(color_negative_values)

In [29]:
df3 = pd.DataFrame({'A': np.random.randn(10), 'B': np.random.randn(10)})
df3

A         B
0 -0.501609  0.705302
1  0.758420  1.189865
2  0.571806  0.135736
3 -0.712923 -0.534653
4  0.009579 -0.085703
5 -2.152851  1.417716
6  0.372404  0.458774
7 -0.753733 -0.446114
8  0.585617  0.386589
9 -0.367636  0.775967

In [30]:
df3.style.applymap(color_negative_values)